
package com.smartbear;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This sample web service is used to demonstrate how to spellservice web services with SmartBear's TestComplete.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SampleWebService", targetNamespace = "http://smartbear.com", wsdlLocation = "http://secure.smartbearsoftware.com/samples/testcomplete10/webservices/Service.asmx?WSDL")
public class SampleWebService
    extends Service
{

    private final static URL SAMPLEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAMPLEWEBSERVICE_EXCEPTION;
    private final static QName SAMPLEWEBSERVICE_QNAME = new QName("http://smartbear.com", "SampleWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://secure.smartbearsoftware.com/samples/testcomplete10/webservices/Service.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAMPLEWEBSERVICE_WSDL_LOCATION = url;
        SAMPLEWEBSERVICE_EXCEPTION = e;
    }

    public SampleWebService() {
        super(__getWsdlLocation(), SAMPLEWEBSERVICE_QNAME);
    }

    public SampleWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAMPLEWEBSERVICE_QNAME, features);
    }

    public SampleWebService(URL wsdlLocation) {
        super(wsdlLocation, SAMPLEWEBSERVICE_QNAME);
    }

    public SampleWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAMPLEWEBSERVICE_QNAME, features);
    }

    public SampleWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SampleWebServiceSoap
     */
    @WebEndpoint(name = "SampleWebServiceSoap")
    public SampleWebServiceSoap getSampleWebServiceSoap() {
        return super.getPort(new QName("http://smartbear.com", "SampleWebServiceSoap"), SampleWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleWebServiceSoap
     */
    @WebEndpoint(name = "SampleWebServiceSoap")
    public SampleWebServiceSoap getSampleWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://smartbear.com", "SampleWebServiceSoap"), SampleWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAMPLEWEBSERVICE_EXCEPTION!= null) {
            throw SAMPLEWEBSERVICE_EXCEPTION;
        }
        return SAMPLEWEBSERVICE_WSDL_LOCATION;
    }

}
